spring:
  datasource:
    url: jdbc:sqlserver://springbootmysqlserver.database.windows.net:1433;database=springbootmysqlDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: mysqluser
    password: Anshu@1884
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 9191
 
    
